QuizCentre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quizapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quizapp/', include('quizapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizapp/urls.py
from django.urls import path
from quizapp import views

app_name = 'quizapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('register/', views.register, name='register'), 
    path('logout/', views.user_logout, name='logout'),
    path('quiz_taker_dashboard/', views.quiz_taker_dashboard, name='quiztaker'),
    path('quiz_maker_dashboard/', views.quiz_maker_dashboard, name='quizmaker'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    path('add_questions/<slug:quiz_slug>/<int:number_of_questions>', views.add_questions, name='add_questions'),
    path('quiz/<slug:quiz_slug>/', views.quiz, name='quiz'),
    path('view_other_quizzes/', views.view_other_quizzes, name='view_other_quizzes'),
    path('quiz_finish/<slug:quiz_slug>/', views.quiz_finish, name='quiz_finish'),
    path('ajax/delete_quiz/<slug:quiz_slug>/', views.ajax_delete_quiz, name='ajax_delete_quiz'), 
    path('view_quiz/<slug:quiz_slug>/', views.view_quiz, name='view_quiz'), 
] 

quizapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify


class User(AbstractUser):
    USER_CHOICES = (
        (1, 'quiz taker'),
        (2, 'quiz maker')
    )

    user_type = models.PositiveSmallIntegerField(choices=USER_CHOICES, default=1)

    def __str__(self):
        return self.username


class QuizTaker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class QuizMaker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Quiz(models.Model):
    number_of_questions = models.PositiveIntegerField()
    max_score = models.PositiveIntegerField()
    topic = models.CharField(max_length=250)
    name = models.CharField(max_length=250, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name_slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.name


class Question(models.Model):
    question_text = models.TextField(max_length=5000)
    image = models.ImageField(upload_to='question_images', blank=True)
    max_score = models.PositiveIntegerField()
    correct_answer = models.TextField(max_length=200)
    incorrect_answer_1 = models.TextField(max_length=200)
    incorrect_answer_2 = models.TextField(max_length=200)
    incorrect_answer_3 = models.TextField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.quiz.name + ": Question " + str(self.id)



class QuizAttempt(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    quiz_maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quiz_author')
    max_score = models.IntegerField()
    actual_score = models.IntegerField()
    quiz_taker = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.quiz.name + " by " + self.quiz_maker.username + str(self.id)


class Answer(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz_taker = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz_attempt = models.ForeignKey(QuizAttempt, on_delete=models.CASCADE)
    max_score = models.IntegerField()
    actual_score = models.IntegerField()
    answer_choice = models.CharField(max_length=500)

    def __str__(self):
        return "answer by " + self.quiz_taker.username + " to question " + str(
            self.question.id) + " from quiz " + self.quiz.name

quizapp/forms.py
from django import forms
from .models import *


class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=30, label="Please enter a username:", required=True)
    password = forms.CharField(max_length=30, label="Please enter a password:", required=True, widget=forms.PasswordInput())
    email = forms.EmailField(label="Please enter an email.", required=True)
    user_type = forms.ChoiceField(initial=0, label = "Would you like to register as a quiz taker or quiz maker?",choices = User.USER_CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'user_type')


class QuizForm(forms.ModelForm):
    TOPICS = (
        ("Java","Java"),
        ("Algorithms","Algorithms"),
        ("Veterinary","Veterinary"),
        ("Mathematics","Mathematics"),
        ("Web App Development","Web App Development"),
        ("English","English"),
    )
    name = forms.CharField(max_length=250, label="Please enter the name of your quiz:")
    topic = forms.ChoiceField(label="Please choose the topic of your quiz", choices = TOPICS)
    number_of_questions = forms.IntegerField(initial=1, label="Please enter the number of questions:",min_value=1)
    name_slug = forms.CharField(widget=forms.HiddenInput, required=False)
    
    class Meta:
        model = Quiz
        fields = ('name','number_of_questions','topic')


class QuestionForm(forms.ModelForm):
    question_text = forms.CharField(max_length=5000, label="Please enter the question:", required=True)
    image = forms.ImageField(label="Image:", required=False, )
    correct_answer = forms.CharField(max_length=200, label="Please enter the correct answer:", required=True)
    incorrect_answer_1 = forms.CharField(max_length=200, label="Please enter the first incorrect answer:")
    incorrect_answer_2 = forms.CharField(max_length=200, label="Please enter the second incorrect answer:")
    incorrect_answer_3 = forms.CharField(max_length=200, label="Please enter the third incorrect answer:")
    max_score = forms.IntegerField(initial=1, label="Please enter the available points for this question:",min_value=1)

    class Meta:
        model = Question
        fields = ('question_text', 'image', 'correct_answer',
                  'incorrect_answer_1', 'incorrect_answer_2', 'incorrect_answer_3','max_score')

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer_choice',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['answer_choice'].widget = forms.RadioSelect(choices=[], attrs={'class': 'form-check-input'})

    def set_choices(self, choices):
        self.fields['answer_choice'].choices = choices

quizapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from .forms import *
from django.forms import formset_factory
from django.shortcuts import get_object_or_404
from .decorators import *
from .models import Quiz, Question


def index(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('quizapp:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'quizapp/index.html', {'username': request.user.username})


def register(request):
    registered = False

    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save()

            user.set_password(user.password)
            user.save()

            if user.user_type == 1:
                profile = QuizTaker.objects.create(user=user)
            else:
                profile = QuizMaker.objects.create(user=user)
            print(form['user_type'].value)

            profile.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            registered = True
            return redirect(reverse('quizapp:index'))
        else:
            print(form.errors)
            messages.error(request, "Unsuccessful registration. Invalid information.")
    else:

        form = UserForm()

    return render(request,
                  'quizapp/register.html',
                  context={'form': form,
                           'registered': registered})


def user_logout(request):
    logout(request)
    return redirect(reverse('quizapp:index'))


@quiz_taker_required
def quiz(request, quiz_slug):
    quiz_instance = get_object_or_404(Quiz, name_slug=quiz_slug)
    questions = Question.objects.filter(quiz=quiz_instance)
    question_data_list = []
    quiz_attempt_score = 0

    for question in questions:
        question_options = [question.correct_answer, question.incorrect_answer_1, question.incorrect_answer_2,
                   question.incorrect_answer_3]
        question_data = {'question': question, 'options': question_options}
        question_data_list.append(question_data)

    if request.method == 'POST':
        for question in questions:
            selected_option = request.POST.get(str(question.id))
            if selected_option == question.correct_answer:
                actual_score = question.max_score
                quiz_attempt_score += question.max_score
            else:
                actual_score = 0
            # update each answer to the current QuizAttempt object
            quiz_attempt = QuizAttempt.objects.update_or_create(
            quiz=quiz_instance,
            quiz_maker=quiz_instance.author,
            max_score=quiz_instance.max_score,
            actual_score=actual_score,
            quiz_taker=request.user
            )[0]
            # create an Answer object for each answer
            answer = Answer.objects.create(
                quiz=quiz_instance,
                question=question,
                answer_choice=selected_option,
                max_score=question.max_score,
                actual_score=quiz_attempt_score,
                quiz_attempt=quiz_attempt,
                quiz_taker=request.user,
            )
            request.session['quiz_attempt_score'] = quiz_attempt_score # store actual score to pass it to the next view
        return redirect(reverse('quizapp:quiz_finish',
                                kwargs = {'quiz_slug' : quiz_slug,}))
    context = {
        'quiz': quiz_instance,
        'questions': questions,
        'number_of_questions': quiz_instance.number_of_questions,
        'quiz_instance': quiz_instance,
        'question_data_list': question_data_list
    }
    return render(request, 'quizapp/quiz.html', context)


@quiz_taker_required
def quiz_finish(request, quiz_slug):
    context = {'quiz_slug' : quiz_slug,
               'score' : request.session.get('quiz_attempt_score') }
    return render(request, 'quizapp/quiz_finish.html',context)

def about(request):
    return render(request, 'quizapp/about.html')


def contact(request):
    return render(request, 'quizapp/contact.html')


@quiz_maker_required
def quiz_maker_dashboard(request):
    has_quizzes = False
    if Quiz.objects.filter(author=request.user).exists():
        has_quizzes = True
    my_quizzes = Quiz.objects.filter(author=request.user)

    context = {'my_quizzes': my_quizzes, 'has_quizzes': has_quizzes}
    return render(request, 'quizapp/quizmaker.html', context)


@quiz_taker_required
def quiz_taker_dashboard(request):
    quizzes_exist = False
    if Quiz.objects.all().exists():
        quizzes_exist = True
    all_quizzes = Quiz.objects.all()

    context = {'all_quizzes': all_quizzes, 'quizzes_exist': quizzes_exist}
    return render(request, 'quizapp/quiztaker.html', context)


@quiz_maker_required
def create_quiz(request):
    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            request.session['quiz_form_data'] = form.cleaned_data
            return redirect(reverse('quizapp:add_questions', kwargs={'quiz_slug': slugify(form.cleaned_data['name']),
                                                                     'number_of_questions': form.cleaned_data['number_of_questions']}))
    else:
        form = QuizForm()

    context = {"form": form, "username": request.user.username}
    return render(request, 'quizapp/create_quiz.html', context)


@quiz_maker_required
def add_questions(request, quiz_slug, number_of_questions):
    my_form_set = formset_factory(QuestionForm, extra=number_of_questions)

    quiz_form_data = request.session.get('quiz_form_data')
    if not quiz_form_data:
        # Redirect to create_quiz view if quiz_form_data not found in session
        return redirect(reverse('quizapp:create_quiz'))

    if request.method == 'POST':
        formset = my_form_set(request.POST, request.FILES)
        if formset.is_valid():
            overall_max_score = 0
            quiz = Quiz.objects.create(name=quiz_form_data['name'],
                                        topic=quiz_form_data['topic'],
                                        number_of_questions=quiz_form_data['number_of_questions'],
                                        max_score=overall_max_score,
                                        author=request.user,
                                        author_id=request.user.id,
                                        name_slug=quiz_slug,)
            for form in formset:
                question = form.save(commit=False)
                question.quiz = quiz
                question.save()
                overall_max_score += question.max_score
            quiz.max_score = overall_max_score
            quiz.save()
            del request.session['quiz_form_data']
            return redirect(reverse('quizapp:quizmaker'))
    else:
        formset = my_form_set()

    return render(request, 'quizapp/add_questions.html', {'formset': formset, "username": request.user.username})

@quiz_maker_required
def view_other_quizzes(request):
    quizzes_exist = False
    if Quiz.objects.all().exists():
        quizzes_exist = True
    all_quizzes = Quiz.objects.all()
    return render(request, 'quizapp/quizzes_list.html', {'all_quizzes' : all_quizzes,
                                                         'quizzes_exist' : quizzes_exist})

@quiz_maker_required
def view_quiz(request, quiz_slug):
    quiz_instance = get_object_or_404(Quiz, name_slug=quiz_slug)
    questions = Question.objects.filter(quiz=quiz_instance)
    question_data_list = []

    for question in questions:
        question_options = [question.correct_answer, question.incorrect_answer_1, question.incorrect_answer_2,
                   question.incorrect_answer_3]
        question_data = {'question': question, 'options': question_options}
        question_data_list.append(question_data)

    context = {
        'quiz': quiz_instance,
        'questions': questions,
        'number_of_questions': quiz_instance.number_of_questions,
        'quiz_instance': quiz_instance,
        'question_data_list': question_data_list
    }
    return render(request, 'quizapp/quiz.html', context)

def ajax_delete_quiz(request, quiz_slug):
    try:
        quiz = Quiz.objects.get(name_slug=quiz_slug)
        quiz.delete()
        print("we got here")
        return JsonResponse({"success": True})
    except Exception as e:
        return JsonResponse({"success": False})

templates/quizapp/about.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    About us
{% endblock %}

{% block css_block %}
	<link rel="stylesheet" href="{% static 'css/about-contact_us.css' %}">
{% endblock %}


{% block body_block %}

    <h1>About us:</h1>
    
    <div class="contents">
    <p> This is the about page! </p>

        <p> Looking for a website that allows you easily set up and distribute quizes? </br>
            Tired of websites that just don't quite work how you want it to? </br>
            Well we've got exactly what you need. Quiz Centre is a website specialising in quizes that is certain to meet all your quiz needs. </p>

        <p> We are a small team that settled on the idea to develop a quiz based website after realising our dissatisfaction with the current options, and </br>
            whilst it hasn't been the smoothest journey getting to this point, we are dedicated to continue forward to make quiz centre the very best it possibly can be.</p>
        <p>
        </p>
    </div>
    
{% endblock %}

templates/quizapp/add_questions.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    QuizCentre
{% endblock %}


{% block css_block %}
    <link rel="stylesheet" href="{% static 'css/add_questions.css' %}">
{% endblock %}

{% block body_block %}

		<h1>Quiz Centre</h1> 
        {% if user.is_authenticated %}
        <p> Currently logged in as {{ username }}</p>   	
        {% endif %}        
		<div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                <div>
                <h2>Question {{ forloop.counter }} </h2> 
                  {{ form.as_p }}
                </div>
                {% endfor %}
                <button type="submit">Save Quiz</button>
              </form>
              
		
		</div>
		
		

{% endblock %}

templates/quizapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Quiz Center - 
            {% block title_block %}
                Quiz Center main
            {% endblock %}
        </title>
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

        {% block css_block %}
            <link rel="stylesheet" href="{% static 'css/base.css' %}">
            <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>
            <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}" type="text/css"/>
		{% endblock %}

    </head>

    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>

        <hr />
        <div class="footer">
            <ul>
                <li><a href="{% url 'quizapp:about' %}">About</a></li>
                <li><a href="{% url 'quizapp:contact' %}">Contact Us</a></li>
                
                {% if user.is_authenticated %}
                	<li><a href="{% url 'quizapp:index' %}">Home</a></li>
                {% else %}
                	<li><a href="{% url 'quizapp:index' %}">Login/Register</a></li>
                {% endif %}
            </ul>
        </div>
    </body>
</html>

templates/quizapp/contact.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    Contact us
{% endblock %}

{% block css_block %}
	<link rel="stylesheet" href="{% static 'css/about-contact_us.css' %}">
{% endblock %}


{% block body_block %}

    <h1>Contact us:</h1>
    
    <div class="contents">
        <p>Although the team working on quiz centre spends day and night searching for bugs and errors it is impossible
            to find them all.
            </br>
            So if you believe you have found a bug during your experience with the quiz centre website
            feel free to send an email or call us, so we can make quiz centre the best it possibly can be.
        </p>
        <p>
            Since quiz centre is still a work in progress, letting us know about any bugs you've found or just your opinions of the website would mean alot.
            Please see our contact details below.
        </p>

    <p> Email: quizapp@gmail.com </br> 
    	Phone: 01234567
    </p>
    </div>
    
{% endblock %}

templates/quizapp/create_quiz.html
<!DOCTYPE html>
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    QuizCentre
{% endblock %}
	

{% block body_block %}

		<h1>Quiz Centre</h1> 
        {% if user.is_authenticated %}
        <p> Currently logged in as {{ username }}</p>   	
        {% endif %}        
		<div>
		<form id="Quiz_Form" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			
			{{ form.as_p }}
			
			<button type="submit" > Proceed to Adding Questions</button>
			
		</form>
		
		</div>
		
		

{% endblock %}

templates/quizapp/index.html
<!DOCTYPE html>
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    QuizCentre
{% endblock %}
	
{% block css_block %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block body_block %}

		<h1>Quiz Centre</h1> 

        {% if user.is_authenticated %}
		<div class="contents">
			<p> Currently logged in as {{ username }}</p>
        
        	{% if user.user_type == 1 %}
        		<a href="{% url 'quizapp:quiztaker' %}">Dashboard</a>
			{% else %}
				<a href="{% url 'quizapp:quizmaker' %}">Dashboard</a>
			{% endif %}
			
			
		<a href="{% url 'quizapp:logout' %}">Logout</a> <br>
		</div>

        	
        {% else %}        
		<div class="form-login">
		<form id="login_form" method="post">
			{% csrf_token %}
			
			<div class="form">
				<label for="form-username">Username:</label>
				<input type="text" class="form-control" id="form-username" name="username" value="" size="50" placeholder="something@example.com"/>
			</div>
			
			<br/>
			<div class="form">
				<label for="form-password">Password:</label>
				<input type="password" class="form-control" id="form-password" name="password" value="" size="50" placeholder="Password"/>
			</div>
			
			<br/>
			
			<div class="contents">
				<input type="submit" id="button-submit" value="Login" />
			</div>
			
		</form>
		
		</div>
		
		<div class="button-register">
			<button type="button">
    			<a href="{% url 'quizapp:register' %}">Register</a>
			</button>
		<div>
		
		{% endif %}

{% endblock %}

templates/quizapp/quiz.html
{% extends 'quizapp/base.html' %}
{% load static %}
{% load quizapp_tags %}

{% block title_block %}
    Quiz question
{% endblock %}

{% block body_block %}

    <h1>Quiz - Basics of Java:</h1>

    <div class="questionbody">
        <form id="question" method="post" action="" enctype="multipart/form-data">
            <div>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {% for question_data in question_data_list %}
                        <h3>{{ question_data.question.question_text }}</h3>
                        {% if question_data.question.image %}
                            <img src="{{ question_data.question.image.url }}" alt="{{ question_data.question.question_text }}" width="400">
                        {% endif %}
                        {% for option in question_data.options|shuffle %}
                            <div>
                                <input type="radio" name="{{ question_data.question.id }}" value="{{ option }}" id="id_{{ option }}">
                                <label for="id_{{ option }}">{{ option }}</label>
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
                {% if request.user.user_type == 1 %}
                <button type="submit">Submit</button>
                {% else %}
            </form>
            <button name="back_to_all_quizzes" class="btn btn-primary" >
                <a href="{% url 'quizapp:view_other_quizzes' %}"
                style="color: white;"
                >Back To All Quizzes</a>
            </button>
            {% endif %}
            </div>
        </form>
    </div>

{% endblock %}

templates/quizapp/quiz_finish.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    Quiz Finished
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'css/'%}">
{% endblock %}

{% block body_block %}

    <div class="main">
        <h2>Quiz Finished!</h2>

        <p class="maintext">
            Your score is {{ score }}
        </p>
        
        <div id="buttons">
            <button name="retake" type="button" class="button">
                <a href="{% url 'quizapp:quiz' quiz_slug=quiz_slug %}">Retake Quiz</a>
            </button>
            <button name="dashboard" type="button" class="button">
                <a href="{% url 'quizapp:quiztaker'%}">Return to dashboard</a>
            </button>
        </div>
    </div>

{% endblock %}

templates/quizapp/quizmaker.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    Quiz Maker Dashboard
{% endblock %}

{% block body_block %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/deleteQuiz.js' %}"></script>
<script>
    var csrf_token = "{{ csrf_token }}";
    deleteQuiz.setCsrfToken(csrf_token);
</script>
    <div class="dashboard">
        <div id="lefthandside">
            <h1>Your Quizzes:</h1>
            <h3>Avg. Score</h3>
            <ul class="your-quizzes-list">
                {% if has_quizzes %}
                {% for quiz in my_quizzes %}
                <li>
                    <div>{{quiz.name}}</div>
                    <div>Number Of Questions: {{quiz.number_of_questions}}</div>
                    <div>Max score: {{quiz.max_score}}</div>
                    <button name="delete" class="button" type="button" onclick="deleteQuiz('{{ quiz.name_slug }}', '{{ csrf_token }}')">Delete Quiz</button>
                </li>
                {% endfor %}
                {% else %}
                    <div>You have no quizzes yet - create one now!</div>
                {% endif %}
            </ul>
        </div>
        <div id="righthandside">
            <button name="view-other" class="button">
                <a href="{% url 'quizapp:view_other_quizzes' %}">View other Quizzes</button>
            <button name="create" class="button"> 
                <a href="{% url 'quizapp:create_quiz' %}"> Create a Quiz</a>
            </button>
        </div>
    </div>

{% endblock %}

templates/quizapp/quiztaker.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block title_block %}
    Quiz Taker Dashboard
{% endblock %}

{% block body_block %}

    <div class="row">
        <div class="col-md-6">
            <h1>Taken Quizzes:</h1>
            <ul class="taken-quizzes-list">
                <li>Quiz 1</li>
                <li>Quiz 2</li>
                <li>Quiz 3</li>
                <li>Quiz 4</li>
            </ul>
        </div>

        <div class="col-md-6">
            <h1>Available Quizzes:</h1>
            <ul class="available-quizzes-list">
                <h2>** INSERT DROPDOWN TO FILTER BY TOPIC **</h2>
                {% if quizzes_exist %}
                {% for quiz in all_quizzes %}
                <li>
                    <div>{{quiz.name}}</div><div>Number Of Questions: {{quiz.number_of_questions}}</div><div>Max score: {{quiz.max_score}}</div>
                    <button name="take_quiz" class="btn btn-primary"> 
                        <a href="{% url 'quizapp:quiz' quiz_slug=quiz.name_slug %}" style="color: white;" >Take this Quiz</a>
                    </button>
                </li>
                {% endfor %}
                {% else %}
                    <div>No quizzes avaiable yet, please come back later.</div>
                {% endif %}
            </ul>
        </div>
    </div>

{% endblock %}

templates/quizapp/quizzes_list.html
{% extends 'quizapp/base.html' %}
{% load static %}
{% load quizapp_tags %}

{% block title_block %}
    Other Quizzes List
{% endblock %}

{% block body_block %}

    <h1>Other Quizzes list</h1>
    <h2 class="text-muted"></h2>
    <br>
    <div id="quizzes-list">
        <ul class="list-group">
            {% if quizzes_exist %}
            {% for quiz in all_quizzes %}
                <li class="list-group-item">
                    <div>{{quiz.name}}</div><div>Number of Questions: {{quiz.number_of_questions}}</div>
                    <button name="view_quiz" class="btn btn-primary" >
                        <a href="{% url 'quizapp:view_quiz' quiz_slug=quiz.name_slug %}"
                        style="color: white;"
                        >View Quiz</a>
                    </button>
                </li>
            {% endfor %}
            {% else %}
                <div>No quizzes available yet, please come back later</div>
            {% endif %}
        </ul>
    </div>
    {% endblock %}

templates/quizapp/register.html
<!DOCTYPE html>
{% load static %}

<html>
	<head> 
		<title>Quiz Centre</title>
	</head>
	
	<body>
		<h1>Quiz Centre</h1> 

		<div>
		<form id="register_form" method="post">
			{% csrf_token %}
			
			{{ form.as_p }}
			
			<input type="submit" value="Register" />
			
		</form>
		
		<br>
		<a href="{% url 'quizapp:index' %}">Back to main page</a>
		
		</div>

	</body>

</html>